FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY prisma ./prisma

RUN npm ci

EXPOSE 3001

CMD ["sh", "-lc", "npm run prisma:generate && npx prisma migrate deploy && npm run dev"]

